project_id = "ricfhnlqurfusvqbtryu"

[functions.generate-program-summary]
verify_jwt = false

[functions.verify-admin-pin]
verify_jwt = false

[functions.create-program]
verify_jwt = false

[functions.update-program]
verify_jwt = false

[functions.set-program-score]
verify_jwt = false
